version: '3.3'

services:

  # Springy Micro Service
  springy:
    container_name: 'springy'
    build:
      context: .
      dockerfile: ./.docker/springy/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mongodb

  # MongoDB
  mongodb:
    container_name: 'mongo'
    build:
      context: .docker/mongodb
    ports:
      - '27017:27017'

  # Mongo Express
  mongo-express:
    image: 'mongo-express:latest'
    container_name: 'mongo-express'
    depends_on:
      - mongodb
    ports:
    - '8081:8081'
